
package com.autodesk.schemas.business.convergentchargingexv1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConvergentChargingExPortType", targetNamespace = "http://www.autodesk.com/schemas/Business/ConvergentChargingExV1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConvergentChargingExPortType {


    /**
     * 
     * @param chargeEventInPart
     * @return
     *     returns com.autodesk.schemas.business.convergentchargingexv1.ResponseType
     * @throws SOAPFault_Exception
     */
    @WebMethod(operationName = "ChargeEvent", action = "ChargeEvent")
    @WebResult(name = "ChargeEventResponse", targetNamespace = "http://www.autodesk.com/schemas/Business/ConvergentChargingExV1.0", partName = "ChargeEventOutPart")
    public ResponseType chargeEvent(
        @WebParam(name = "ChargeEventRequest", targetNamespace = "http://www.autodesk.com/schemas/Business/ConvergentChargingExV1.0", partName = "ChargeEventInPart")
        ChargeDataType chargeEventInPart)
        throws SOAPFault_Exception
    ;

    /**
     * 
     * @param getCcTransactionsInPart
     * @return
     *     returns com.autodesk.schemas.business.convergentchargingexv1.GetCcTransactionsResponse
     * @throws SOAPFault_Exception
     */
    @WebMethod(operationName = "GetCcTransactions", action = "GetCcTransactions")
    @WebResult(name = "GetCcTransactionsResponse", targetNamespace = "http://www.autodesk.com/schemas/Business/ConvergentChargingExV1.0", partName = "GetCcTransactionsOutPart")
    public GetCcTransactionsResponse getCcTransactions(
        @WebParam(name = "GetCcTransactionsRequest", targetNamespace = "http://www.autodesk.com/schemas/Business/ConvergentChargingExV1.0", partName = "GetCcTransactionsInPart")
        GetCcTransactionsRequest getCcTransactionsInPart)
        throws SOAPFault_Exception
    ;

    /**
     * 
     * @param getCcTransactionSummaryInPart
     * @return
     *     returns com.autodesk.schemas.business.convergentchargingexv1.GetCcTransactionSummaryResponse
     * @throws SOAPFault_Exception
     */
    @WebMethod(operationName = "GetCcTransactionSummary", action = "GetCcTransactionSummary")
    @WebResult(name = "GetCcTransactionSummaryResponse", targetNamespace = "http://www.autodesk.com/schemas/Business/ConvergentChargingExV1.0", partName = "GetCcTransactionSummaryOutPart")
    public GetCcTransactionSummaryResponse getCcTransactionSummary(
        @WebParam(name = "GetCcTransactionSummaryRequest", targetNamespace = "http://www.autodesk.com/schemas/Business/ConvergentChargingExV1.0", partName = "GetCcTransactionSummaryInPart")
        GetCcTransactionSummaryRequest getCcTransactionSummaryInPart)
        throws SOAPFault_Exception
    ;

    /**
     * 
     * @param querySubscriptionBalanceInPart
     * @return
     *     returns com.autodesk.schemas.business.convergentchargingexv1.QuerySubscriptionBalanceResponse
     * @throws SOAPFault_Exception
     */
    @WebMethod(action = "querySubscriptionBalance")
    @WebResult(name = "QuerySubscriptionBalanceResponse", targetNamespace = "http://www.autodesk.com/schemas/Business/ConvergentChargingExV1.0", partName = "QuerySubscriptionBalanceOutPart")
    public QuerySubscriptionBalanceResponse querySubscriptionBalance(
        @WebParam(name = "QuerySubscriptionBalanceRequest", targetNamespace = "http://www.autodesk.com/schemas/Business/ConvergentChargingExV1.0", partName = "QuerySubscriptionBalanceInPart")
        QuerySubscriptionBalanceRequest querySubscriptionBalanceInPart)
        throws SOAPFault_Exception
    ;

    /**
     * 
     * @param getCcUsageSummaryInPart
     * @return
     *     returns com.autodesk.schemas.business.convergentchargingexv1.GetCcUsageSummaryResponse
     * @throws SOAPFault_Exception
     */
    @WebMethod(operationName = "GetCcUsageSummary", action = "GetCcUsageSummary")
    @WebResult(name = "GetCcUsageSummaryResponse", targetNamespace = "http://www.autodesk.com/schemas/Business/ConvergentChargingExV1.0", partName = "GetCcUsageSummaryOutPart")
    public GetCcUsageSummaryResponse getCcUsageSummary(
        @WebParam(name = "GetCcUsageSummaryRequest", targetNamespace = "http://www.autodesk.com/schemas/Business/ConvergentChargingExV1.0", partName = "GetCcUsageSummaryInPart")
        GetCcUsageSummaryRequest getCcUsageSummaryInPart)
        throws SOAPFault_Exception
    ;

}
