
package com.autodesk.schemas.business.convergentchargingexv1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SOAPFault", targetNamespace = "http://www.autodesk.com/schemas/Business/ConvergentChargingExV1.0")
public class SOAPFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SOAPFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public SOAPFault_Exception(String message, SOAPFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public SOAPFault_Exception(String message, SOAPFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.autodesk.schemas.business.convergentchargingexv1.SOAPFault
     */
    public SOAPFault getFaultInfo() {
        return faultInfo;
    }

}
