
package com.autodesk.ws.user._1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SOAPFault", targetNamespace = "http://www.autodesk.com/schemas/Technical/CommonV2.0")
public class SOAPFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.autodesk.schemas.technical.commonv2.SOAPFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public SOAPFault(String message, com.autodesk.schemas.technical.commonv2.SOAPFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public SOAPFault(String message, com.autodesk.schemas.technical.commonv2.SOAPFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.autodesk.schemas.technical.commonv2.SOAPFault
     */
    public com.autodesk.schemas.technical.commonv2.SOAPFault getFaultInfo() {
        return faultInfo;
    }

}
